name = "secrets-worker-v2"
compatibility_date = "2024-04-04"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./.vercel/output/static"
send_metrics = false

[env.production.vars]
ENVIRONMENT = "production"

[[env.production.kv_namespaces]]
binding = "SECRETS"
id = "3b25e2a1ac5b4c08bff1590bb8632659"

[[kv_namespaces]]
binding = "SECRETS"
id = "4db3135551414dd4ab3563efca989b8e"

[vars]
ENVIRONMENT = "preview"
